name: maven-hello-world
run-name: ${{ github.actor }} is learning GitHub Actions
on: [push]

jobs:
    version:
        runs-on: ubuntu-latest
        steps:
        - uses: actions/checkout@v4
        - name: Set up JDK 17
          uses: actions/setup-java@v4
          with:
            java-version: '17'
            distribution: 'temurin'
            cache: maven
          
        - name: update version with Maven
          run: mvn --batch-mode release:update-versions
         
        - name: Package
          run: mvn -B package --file pom.xml