name: Maven CI
on: [push]

jobs:
    build-and-push:
        runs-on: ubuntu-latest
        steps:
        
        - uses: actions/checkout@v4
          name: Checkout
        
        # read about setup-java action and its with parameters (specifically cache and distri)
        - name: Set up JDK 17
          uses: actions/setup-java@v4
          with:
            java-version: '17'
            distribution: 'temurin'
            cache: maven
 
        - name: update version with Maven
          run: mvn -B release:update-versions --file ./myapp/pom.xml
      
        - name: Get Version
          id: get-version
          run: |
            VERSION=$(mvn help:evaluate -f ./myapp/pom.xml -Dexpression=project.version -q -DforceStdout) # understand this command
            echo "version=$VERSION" >> $GITHUB_OUTPUT

        - name: Login to Docker Hub
          uses: docker/login-action@v3
          with:
            username: ${{ secrets.DOCKER_USERNAME }}
            password: ${{ secrets.DOCKER_PASSWORD }}
          
          # check if this stage is neccesary 
        - name: Set up Docker Buildx
          uses: docker/setup-buildx-action@v3
            
        - name: Build and push
          uses: docker/build-push-action@v5
          with:
            context: ./myapp
            build-args: |
              VERSION=${{steps.get-version.outputs.version}}
            push: true
            tags: barryallen696/maven:${{steps.get-version.outputs.version}}
