name: maven-hello-world
on: [push]

jobs:
    version-job:
        runs-on: ubuntu-latest
        outputs:
            output1: ${{steps.Version.outputs.version}}
        steps:
        - uses: actions/checkout@v4
        - name: Set up JDK 17
          uses: actions/setup-java@v4
          with:
            java-version: '17'
            distribution: 'temurin'
            cache: maven
        - name: update version with Maven
          run: mvn -B release:update-versions --file ./myapp/pom.xml
        - name: Version
          run: |
            VERSION=$(mvn help:evaluate -Dexpression=project.version -q -DforceStdout)
            echo $VERSION
            echo "version=$VERSION" >> "$GITHUB_OUTPUT"
           
         
    build-and-push:
        runs-on: ubuntu-latest
        needs: version-job
        steps:
            - name: Set up Docker Buildx
              uses: docker/setup-buildx-action@v3
            - name: Login to Docker Hub
              uses: docker/login-action@v3
              with:
                username: ${{DOCKER_USERNAME}}
                password: ${{DOCKER_PASSWORD}}
            - env:
                VERSION: ${{needs.version-job.outputs.version}}
              name: Build and push
              uses: docker/build-push-action@v5
              with:
                context: .
                push: true
                tags: barryallen696/maven:69
         
          
 # multi-stage dockerfile example: https://stackoverflow.com/questions/27767264/how-to-dockerize-maven-project-and-how-many-ways-to-accomplish-it
 # marketplace: https://github.com/marketplace
 # build and push action: https://github.com/marketplace/actions/build-and-push-docker-images#examples